# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
default_platform(:ios)

platform :ios do
  desc "Run tests"
  lane :tests do
    run_tests(
      package_path: ".",
      scheme: "PlayolaPlayer",
      devices: ["iPhone 14"],
      prelaunch_simulator: true,
      result_bundle: true
    )
  end

  desc "Run SwiftLint"
  lane :lint do
    swiftlint(
      mode: :lint,
      config_file: ".swiftlint.yml",
      strict: true
    )
  end
end